# Generated by Django 3.1.4 on 2020-12-27 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualri', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
