# Generated by Django 3.1.4 on 2021-01-24 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visualri', '0002_auto_20201227_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics')),
                ('action', models.CharField(choices=[('NO_FILTER', 'No Filter'), ('RGB', 'RGB'), ('HSV', 'HSV'), ('GRAYSCALE', 'Grayscale'), ('COLORIZED', 'Colorized'), ('BLURRED', 'Blur'), ('MEDIAN BLUR', 'Median Blur'), ('SUPERRES', 'Super Res'), ('POLARIZE', 'Polarize'), ('COOLING', 'Cooling Filter'), ('WARMING', 'Warming Filter'), ('BRIGHTNESS', 'Brightness'), ('CONTRAST', 'Contrast'), ('STYLIZATION', 'Stylization'), ('DETAIL ENHANCE', 'Detail Enhance'), ('COLOR SKETCH', 'Color Sketch'), ('EDGE PRESERVING FILTER', 'Edge Preserving Filter')], default='NO_FILTER', max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
