# Generated by Django 3.1.4 on 2021-01-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualri', '0004_auto_20210125_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='action',
            field=models.CharField(choices=[('THRESHOLDING', 'Thresholding'), ('BGR', 'BGR'), ('HSV', 'HSV'), ('GRAYSCALE', 'Grayscale'), ('STYLIZATION', 'Stylization'), ('DETAIL ENHANCE', 'Detail Enhance'), ('COLOR SKETCH', 'Color Sketch'), ('BLURRED', 'Bipolar Blur'), ('MEDIAN BLUR', 'Median Blur'), ('POLARIZE', 'Polarize'), ('EDGE PRESERVING FILTER', 'Edge Preserving Filter'), ('BRIGHTNESS', 'Brightness'), ('CONTRAST', 'Contrast'), ('COLORIZED', 'Colorize BW image'), ('SUPERRES', 'Super Resolution')], default='POLARIZE', max_length=50),
        ),
    ]
