# Generated by Django 3.1.3 on 2021-01-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_choice',
            field=models.CharField(choices=[('1', 'Camera'), ('2', 'IP Webcam')], default='1', max_length=50),
        ),
    ]
