# Generated by Django 3.1.4 on 2021-01-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostream', '0002_auto_20210122_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='action',
            field=models.CharField(default='FACES', max_length=50),
        ),
    ]
