# Generated by Django 3.1.4 on 2021-01-26 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videostream', '0003_video_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
